name: generators_lite
description: Use the power of automatic code generation for Dart.
repository: https://github.com/Jlgtri/generators_lite
version: 1.0.3+3
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^5.12.0
  args: ^2.4.1
  build: ^2.4.0
  collection: ^1.17.1
  dart_style: ^2.3.1
  glob: ^2.1.1
  json5: ^0.8.0
  meta: ^1.9.1
  path: ^1.8.3
  yaml: ^3.1.2

dev_dependencies:
  build_runner: any

executables:
  generate: main
