name: generators
description: Use the power of automatic code generation for Dart.
repository: https://github.com/Jlgtri/generators
version: 1.0.0
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  analyzer: ^5.4.0
  args: ^2.3.2
  build: ^2.3.1
  collection: ^1.17.1
  dart_style: ^2.2.4
  glob: ^2.1.1
  intl: ^0.18.0
  json5: ^0.8.0
  logging: ^1.1.1
  meta: ^1.9.0
  path: ^1.8.3
  pub_semver: ^2.1.3
  yaml: ^3.1.1

dev_dependencies:
  build_runner: any

executables:
  generate: main
